version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: protobuf
    versions:
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: mysql-connector-python
    versions:
    - 8.0.23
